---
abstract: ~
author:
  - 'Robert ''phaylon' Sedlacek <rs@474.at>'
build_requires:
  Class::Accessor::Fast: 0
  Test::Class: 0
  Test::Most: 0
  self: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Script-SXC
no_index:
  directory:
    - examples
    - inc
    - t
    - examples
requires:
  CLASS: 0
  Data::Dump: 0
  Method::Signatures: 0.02
  Moose: 0.57
  MooseX::AttributeHelpers: 0.13
  MooseX::Types: 0.05
  aliased: 0
  namespace::clean: 0.08
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
